version: '3.8'
services:
  postgres:
    image: postgres:alpine
    env_file:
      - ./backend/.env
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:8080"
    volumes:
      - ./backend:/app/backend
    restart: always

  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    volumes:
      - ./frontend:/app/frontend
    restart: always



  
