# Generated by Django 5.0.4 on 2024-04-30 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_confirmed',
            new_name='is_veryfied',
        ),
    ]
